#!/bin/bash
#Skript apache paigaldamiseks
# 
teenus="apache2"

if dpkg-query -W -f='${Status}' $teenus 2>/dev/null | grep -q "ok installed"; then
    echo "Teenus $teenus on juba paigaldatud."    
    service_status=$(systemctl is-active $teenus)
    echo "Apache: $service_status"
else
    apt update
    apt install -y $teenus

    echo "$teenus on edukalt paigaldatud."
    teenuse_olek=$(systemctl is-active $teenus)
    echo "Teenuse olek: $teenuse_olek"
fi

