#!/bin/bash

#Skript kasutajate lisamiseks failist koos paroolidega

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 paroolid"
else
	paroolid=$1
	if [ -f $paroolid -a -r $paroolid ]; then
	echo "Fail on korras"
	for rida in $(cat $paroolid)
	do
	kasutajanimi=$(echo "$rida"| cut -f1 -d:)
	sh lisa_kasutajad $kasutajanimi
	echo "$rida" chpasswd
	done
else
	echo "Probleem failiga $failinimi"
  fi
fi
